version: '3.1'
services:
  app:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - bdd:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=kinect
      - POSTGRES_USER=kinect
      - POSTGRES_DB=kinect

volumes:
  bdd: