version: '3.1'
services:
  app:
    container_name: postgresql
    image: postgresql
    build: ./
    ports:
      - "7070:7070"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=kinect
      - POSTGRES_USER=kinect
      - POSTGRES_DB=kinect