ALTER TABLE ENREGISTREMENT DROP CONSTRAINT FK_ENREGISTREMENT_CATEGORIE_ID
ALTER TABLE FRAME DROP CONSTRAINT FK_FRAME_ENREGISTREMENT_ID
ALTER TABLE JOINTURE DROP CONSTRAINT FK_JOINTURE_FRAME_ID
DROP TABLE ENREGISTREMENT
DROP TABLE CATEGORIE
DROP TABLE FRAME
DROP TABLE JOINTURE
